[project]
name = "whisper-vdi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jiwer>=3.1.0",
    "pandas>=2.2.3",
    "torch>=2.6.0",
    "webvtt-py>=0.5.1",
    "whisperx>=3.3.1",
]
